name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3

        env:
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
          ADMINNAME: ${{secrets.PASSWORD}}
          PASSWORD_DB: ${{secrets.PASSWORD_DB}}
          PORT_DB: ${{secrets.PORT_DB}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        
      - name: Move to backend and run
        working-directory: ./backend
        run: |
          npm i 
          node app.js

      - name: Run frontend
        working-directory: ./frontend
        run: |
          npm i -g live-server
          npm i
          live-server ./content/Viewer/login.html
          
      - name: Move to backend and run tests
        working-directory: ./backend
        run: |
          node crudTest.js

          exit_code=$?
  
            if [ $exit_code -ne 0 ]; then
              echo "Selenium tests failed. Raising a bug "
                  
                  - name: GitHub Action to create an Azure DevOps Bug Workitem when a workflow fails
                    uses: stefanstranger/azuredevops-bug-action@1.1
                  with:
                    OrganizationName: ${{secrets.ORGNAME}
                    PAT: ${{secrets.PAT}}
                    ProjectName: raise_a_bug
                    AreaPath: selenium_tests
                    IterationPath: frontend
                    GithubToken: ${{secrets.GITHUB_TOKEN}}

            else
              echo "Selenium tests passed."
            fi

            
      
