name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1

      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "PORT=${{secrets.PORT}}" > ./backend/.env
          echo "SECRET=${{secrets.SECRET}}" >> ./backend/.env
          echo "ADMINNAME=${{secrets.PASSWORD}}" >> ./backend/.env
          echo "PASSWORD_DB=${{secrets.PASSWORD_DB}}" >> ./backend/.env
          echo "PORT_DB=${{secrets.PORT_DB}}" >> ./backend/.env

      - name: Move to backend and run
        run: |
          cd ./backend
          npm i 
          node app.js &

      - name: Run frontend
        run: |
          cd ./../frontend
          npm i -g live-server
          npm i
          live-server ./content/Viewer/login.html
          
      - name: Move to backend and run tests
        run: |
          cd ./../backend/selenium_tests
          node crudTest.js
          exit_code=$?
  
          if [ $exit_code -ne 0 ]; then
            echo "Selenium tests failed. Raising a bug "
            
            - name: GitHub Action to create an Azure DevOps Bug Workitem when a workflow fails
              uses: stefanstranger/azuredevops-bug-action@1.1
              with:
                OrganizationName: ${{secrets.ORGNAME}}
                PAT: ${{secrets.PAT}}
                ProjectName: raise_a_bug
                AreaPath: selenium_tests
                IterationPath: frontend
                GithubToken: ${{secrets.GITHUB_TOKEN}}
          else
            echo "Selenium tests passed."
          fi
