name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        
      - name: Move to backend and run
        run: |
          cd ./backend
          npm i 
          node app.js

      - name: Run frontend
        run: |
          cd ./../frontend
          npm i -g live-server
          live-server ./content/Viewer/login.html
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  backend:
    runs-on: ubuntu-latest
    needs:
      - build

      
  frontend:
    runs-on: ubuntu-latest
    needs:
      - build

  test:
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend


  strategy:
    matrix:
      os: [ubuntu-latest]
    
